# Generated by Django 5.2.11 on 2026-02-21 03:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Specialty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("client", "Client"),
                            ("practitioner", "Practitioner"),
                        ],
                        default="client",
                        max_length=50,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Format: +254712345678",
                        max_length=20,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in format: '+254712345678' (up to 15 digits)",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Practitioner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "currency",
                    models.CharField(
                        choices=[("KES", "Kenyan Shilling"), ("USD", "US Dollar")],
                        default="KES",
                        max_length=3,
                    ),
                ),
                (
                    "hourly_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        help_text="Hourly rate in selected currency",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("bio", models.TextField(blank=True, null=True)),
                (
                    "city",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=100
                    ),
                ),
                ("years_of_experience", models.PositiveIntegerField(default=0)),
                ("is_verified", models.BooleanField(db_index=True, default=False)),
                ("profile_complete", models.BooleanField(default=False)),
                (
                    "specialties",
                    models.ManyToManyField(
                        related_name="practitioner", to="NutriApp.specialty"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practitioner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Consultation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(db_index=True)),
                ("time", models.TimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("booked", "Booked"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                        ],
                        default="booked",
                        max_length=50,
                    ),
                ),
                ("duration_minutes", models.PositiveIntegerField(default=60)),
                ("client_notes", models.TextField(blank=True, null=True)),
                ("practitioner_notes", models.TextField(blank=True, null=True)),
                (
                    "version",
                    models.IntegerField(
                        default=1,
                        help_text="Optimistic locking version field to prevent double booking",
                    ),
                ),
                (
                    "practitioner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultations",
                        to="NutriApp.practitioner",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        limit_choices_to={"profile__role": "client"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-time"],
            },
        ),
        migrations.CreateModel(
            name="Availability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recurrence_type",
                    models.CharField(
                        choices=[
                            ("weekly", "Weekly Recurring"),
                            ("one_time", "One-Time Adjustment"),
                            ("unavailable", "Unavailable Block"),
                        ],
                        default="weekly",
                        max_length=20,
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        help_text="For weekly recurring availability (0=Monday, 6=Sunday)",
                        null=True,
                    ),
                ),
                (
                    "specific_date",
                    models.DateField(
                        blank=True,
                        help_text="For one-time availability or unavailable blocks",
                        null=True,
                    ),
                ),
                ("start_time", models.TimeField(help_text="Format: HH:MM:SS")),
                ("end_time", models.TimeField(help_text="Format: HH:MM:SS")),
                (
                    "is_available",
                    models.BooleanField(
                        default=True,
                        help_text="False for unavailable blocks (vacation, time off, holidays)",
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True,
                        help_text="Reason for unavailability (e.g., 'Vacation', 'Conference', 'Public Holiday')",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "practitioner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availabilities",
                        to="NutriApp.practitioner",
                    ),
                ),
            ],
            options={
                "ordering": ["practitioner", "day_of_week", "start_time"],
                "indexes": [
                    models.Index(
                        fields=["practitioner", "recurrence_type"],
                        name="NutriApp_av_practit_4cfa11_idx",
                    ),
                    models.Index(
                        fields=["practitioner", "specific_date"],
                        name="NutriApp_av_practit_06e9cc_idx",
                    ),
                    models.Index(
                        fields=["practitioner", "day_of_week"],
                        name="NutriApp_av_practit_1c8ee8_idx",
                    ),
                    models.Index(
                        fields=["practitioner", "is_available"],
                        name="NutriApp_av_practit_f721ed_idx",
                    ),
                    models.Index(
                        fields=["specific_date", "is_available"],
                        name="NutriApp_av_specifi_5a8b66_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "consultation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review",
                        to="NutriApp.consultation",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["consultation", "rating"],
                        name="NutriApp_re_consult_d50522_idx",
                    ),
                    models.Index(
                        fields=["reviewer", "created_at"],
                        name="NutriApp_re_reviewe_14e3f2_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="practitioner",
            index=models.Index(
                fields=["city", "is_verified"], name="NutriApp_pr_city_9188af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="practitioner",
            index=models.Index(
                fields=["years_of_experience", "hourly_rate"],
                name="NutriApp_pr_years_o_0fc57f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="practitioner",
            index=models.Index(
                fields=["is_verified", "city"], name="NutriApp_pr_is_veri_0695b7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="consultation",
            index=models.Index(
                fields=["client", "status"], name="NutriApp_co_client__6414f5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="consultation",
            index=models.Index(
                fields=["practitioner", "status"], name="NutriApp_co_practit_21c519_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="consultation",
            index=models.Index(
                fields=["date", "status"], name="NutriApp_co_date_0e421a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="consultation",
            index=models.Index(
                fields=["client", "date"], name="NutriApp_co_client__45e6a0_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="consultation",
            unique_together={("practitioner", "date", "time")},
        ),
    ]
