# Generated by Django 6.0 on 2026-02-24 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NutriApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='practitionerapplication',
            name='NutriApp_pr_status_85b424_idx',
        ),
        migrations.RemoveIndex(
            model_name='practitionerapplication',
            name='NutriApp_pr_user_id_3ee8dc_idx',
        ),
        migrations.DeleteModel(
            name='PractitionerApplication',
        ),
    ]
