# Generated by Django 4.2 on 2026-02-22 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("NutriApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PractitionerApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("info_needed", "More Info Needed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "qualifications",
                    models.TextField(
                        help_text="List your qualifications and certifications"
                    ),
                ),
                (
                    "experience_description",
                    models.TextField(help_text="Describe your relevant experience"),
                ),
                (
                    "id_document",
                    models.FileField(
                        blank=True, null=True, upload_to="applications/id/"
                    ),
                ),
                (
                    "certification_documents",
                    models.FileField(
                        blank=True, null=True, upload_to="applications/certifications/"
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True, help_text="Internal notes for admin", null=True
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True, help_text="Reason if rejected", null=True
                    ),
                ),
                (
                    "practitioner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="application",
                        to="NutriApp.practitioner",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.AddIndex(
            model_name="practitionerapplication",
            index=models.Index(
                fields=["status", "submitted_at"], name="NutriApp_pr_status_0aaf72_idx"
            ),
        ),
    ]
