# Generated by Django 6.0 on 2026-02-23 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NutriApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('consultation_request', 'New Consultation Request'), ('consultation_confirmed', 'Consultation Confirmed'), ('consultation_cancelled', 'Consultation Cancelled'), ('consultation_completed', 'Consultation Completed'), ('review_received', 'New Review Received'), ('payment_received', 'Payment Received'), ('practitioner_verified', 'Account Verified'), ('system', 'System Notification')], db_index=True, max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='NutriApp_no_recipie_e0c990_idx'), models.Index(fields=['recipient', 'is_read'], name='NutriApp_no_recipie_e83e10_idx')],
            },
        ),
    ]
