# Generated by Django 6.0 on 2026-02-24 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NutriApp', '0002_remove_practitionerapplication_nutriapp_pr_status_85b424_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PractitionerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('professional_title', models.CharField(max_length=200)),
                ('qualifications', models.TextField(help_text='List your qualifications and certifications')),
                ('experience_description', models.TextField(help_text='Describe your relevant experience')),
                ('specialized_areas', models.CharField(blank=True, max_length=500)),
                ('id_document', models.FileField(upload_to='applications/ids/')),
                ('certification_documents', models.FileField(upload_to='applications/certifications/')),
                ('profile_photo', models.ImageField(upload_to='applications/photos/')),
                ('linkedin_url', models.URLField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('data_consent_given', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('practitioner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='NutriApp.practitioner')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
