# Generated by Django 6.0 on 2026-02-23 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NutriApp', '0002_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='practitionerapplication',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='practitionerapplication',
            name='NutriApp_pr_status_0aaf72_idx',
        ),
        migrations.AddField(
            model_name='practitionerapplication',
            name='data_consent_given',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='practitionerapplication',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='practitionerapplication',
            name='professional_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='practitionerapplication',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='applications/photos/'),
        ),
        migrations.AddField(
            model_name='practitionerapplication',
            name='specialized_areas',
            field=models.CharField(blank=True, help_text='Comma-separated list of specialized areas', max_length=500),
        ),
        migrations.AddField(
            model_name='practitionerapplication',
            name='terms_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='practitionerapplication',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='practitioner_application', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='practitionerapplication',
            name='website_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='practitionerapplication',
            name='practitioner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application', to='NutriApp.practitioner'),
        ),
        migrations.AlterField(
            model_name='practitionerapplication',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft - Not Submitted'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('info_needed', 'More Info Needed')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='practitionerapplication',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='practitionerapplication',
            index=models.Index(fields=['status', 'created_at'], name='NutriApp_pr_status_85b424_idx'),
        ),
        migrations.AddIndex(
            model_name='practitionerapplication',
            index=models.Index(fields=['user', 'status'], name='NutriApp_pr_user_id_3ee8dc_idx'),
        ),
    ]
