# Generated by Django 5.2.11 on 2026-02-21 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("NutriApp", "0002_add_practitioner_application"),
        ("NutriApp", "0002_alter_practitioner_specialties_and_more"),
    ]

    operations = []
