# Generated by Django 6.0 on 2026-02-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NutriApp', '0004_populate_reviewers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='practitioner',
            old_name='rate',
            new_name='hourly_rate',
        ),
        migrations.AddField(
            model_name='practitioner',
            name='currency',
            field=models.CharField(choices=[('KES', 'Kenyan Shilling'), ('USD', 'US Dollar')], default='KES', max_length=3),
        ),
    ]
