# Generated by Django 6.0 on 2026-02-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NutriApp', '0005_rename_rate_practitioner_hourly_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='consultation',
            unique_together={('practitioner', 'date', 'time')},
        ),
    ]
