# Generated by Django 6.0 on 2026-02-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NutriApp', '0007_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('practitioner', 'Practitioner')], default='client', max_length=50),
        ),
    ]
