# Generated by Django 6.0 on 2026-02-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NutriApp', '0008_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='practitioner',
            name='city',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='practitioner',
            name='experience_level',
            field=models.CharField(default='Entry Level', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='practitioner',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
