<<<<<<< HEAD
# Generated by Django 6.0 on 2026-02-17 12:47

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models
=======
# Generated by Django 4.2 on 2026-02-17 14:04

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
>>>>>>> 62b8934b93c5a704d48d4b45c7247d957b766c97


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('NutriApp', '0009_practitioner_city_practitioner_experience_level_and_more'),
=======
        ("NutriApp", "0009_practitioner_city_practitioner_experience_level_and_more"),
>>>>>>> 62b8934b93c5a704d48d4b45c7247d957b766c97
    ]

    operations = [
        migrations.AlterModelOptions(
<<<<<<< HEAD
            name='availability',
            options={'ordering': ['day_of_week', 'start_time']},
        ),
        migrations.AlterModelOptions(
            name='consultation',
            options={'ordering': ['-date', '-time']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='specialty',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='practitioner',
            name='experience_level',
        ),
        migrations.AddField(
            model_name='consultation',
            name='client_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 2, 17, 12, 46, 13, 938437, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultation',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='consultation',
            name='practitioner_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='practitioner',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='practitioner',
            name='profile_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='practitioner',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='practitioner',
            name='years_of_experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='client',
            field=models.ForeignKey(limit_choices_to={'profile__role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='booked', max_length=50),
        ),
        migrations.AlterField(
            model_name='practitioner',
            name='city',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='practitioner',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='practitioner',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='practitioner',
            name='specialties',
            field=models.ManyToManyField(related_name='practitioner', to='NutriApp.specialty'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together={('practitioner', 'day_of_week', 'start_time')},
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['client', 'status'], name='NutriApp_co_client__6414f5_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['practitioner', 'status'], name='NutriApp_co_practit_21c519_idx'),
        ),
        migrations.AddIndex(
            model_name='practitioner',
            index=models.Index(fields=['city', 'is_verified'], name='NutriApp_pr_city_9188af_idx'),
        ),
        migrations.AddIndex(
            model_name='practitioner',
            index=models.Index(fields=['years_of_experience', 'hourly_rate'], name='NutriApp_pr_years_o_0fc57f_idx'),
=======
            name="availability",
            options={"ordering": ["day_of_week", "start_time"]},
        ),
        migrations.AlterModelOptions(
            name="consultation",
            options={"ordering": ["-date", "-time"]},
        ),
        migrations.AlterModelOptions(
            name="review",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="specialty",
            options={"ordering": ["name"]},
        ),
        migrations.RemoveField(
            model_name="practitioner",
            name="experience_level",
        ),
        migrations.AddField(
            model_name="consultation",
            name="client_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="consultation",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2026, 2, 17, 14, 3, 48, 194221, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="consultation",
            name="duration_minutes",
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name="consultation",
            name="practitioner_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="consultation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="practitioner",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="practitioner",
            name="profile_complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="practitioner",
            name="updated_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="practitioner",
            name="years_of_experience",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="availability",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="consultation",
            name="client",
            field=models.ForeignKey(
                limit_choices_to={"profile__role": "client"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consultations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="consultation",
            name="date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="consultation",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="consultation",
            name="status",
            field=models.CharField(
                choices=[
                    ("booked", "Booked"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("no_show", "No Show"),
                ],
                default="booked",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="practitioner",
            name="city",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="practitioner",
            name="hourly_rate",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="practitioner",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="practitioner",
            name="is_verified",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="practitioner",
            name="specialties",
            field=models.ManyToManyField(
                related_name="practitioner", to="NutriApp.specialty"
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.PositiveSmallIntegerField(
                choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="specialty",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="specialty",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="availability",
            unique_together={("practitioner", "day_of_week", "start_time")},
        ),
        migrations.AddIndex(
            model_name="consultation",
            index=models.Index(
                fields=["client", "status"], name="NutriApp_co_client__6414f5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="consultation",
            index=models.Index(
                fields=["practitioner", "status"], name="NutriApp_co_practit_21c519_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="practitioner",
            index=models.Index(
                fields=["city", "is_verified"], name="NutriApp_pr_city_9188af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="practitioner",
            index=models.Index(
                fields=["years_of_experience", "hourly_rate"],
                name="NutriApp_pr_years_o_0fc57f_idx",
            ),
>>>>>>> 62b8934b93c5a704d48d4b45c7247d957b766c97
        ),
    ]
