# Generated by Django 6.0.2 on 2026-02-20 21:09

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NutriApp', '0013_alter_availability_id_alter_consultation_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availability',
            options={'ordering': ['practitioner', 'day_of_week', 'start_time']},
        ),
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='availability',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='availability',
            name='is_available',
            field=models.BooleanField(default=True, help_text='False for unavailable blocks (vacation, time off, holidays)'),
        ),
        migrations.AddField(
            model_name='availability',
            name='notes',
            field=models.CharField(blank=True, help_text="Reason for unavailability (e.g., 'Vacation', 'Conference', 'Public Holiday')", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='availability',
            name='recurrence_type',
            field=models.CharField(choices=[('weekly', 'Weekly Recurring'), ('one_time', 'One-Time Adjustment'), ('unavailable', 'Unavailable Block')], default='weekly', max_length=20),
        ),
        migrations.AddField(
            model_name='availability',
            name='specific_date',
            field=models.DateField(blank=True, help_text='For one-time availability or unavailable blocks', null=True),
        ),
        migrations.AddField(
            model_name='availability',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='availability',
            name='day_of_week',
            field=models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='For weekly recurring availability (0=Monday, 6=Sunday)', null=True),
        ),
        migrations.AlterField(
            model_name='availability',
            name='end_time',
            field=models.TimeField(help_text='Format: HH:MM:SS'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='start_time',
            field=models.TimeField(help_text='Format: HH:MM:SS'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='version',
            field=models.IntegerField(default=1, help_text='Optimistic locking version field to prevent double booking'),
        ),
        migrations.AlterField(
            model_name='practitioner',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, help_text='Hourly rate in selected currency', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='practitioner',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, help_text='Format: +254712345678', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in format: '+254712345678' (up to 15 digits)", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddIndex(
            model_name='availability',
            index=models.Index(fields=['practitioner', 'recurrence_type'], name='NutriApp_av_practit_4cfa11_idx'),
        ),
        migrations.AddIndex(
            model_name='availability',
            index=models.Index(fields=['practitioner', 'specific_date'], name='NutriApp_av_practit_06e9cc_idx'),
        ),
        migrations.AddIndex(
            model_name='availability',
            index=models.Index(fields=['practitioner', 'day_of_week'], name='NutriApp_av_practit_1c8ee8_idx'),
        ),
        migrations.AddIndex(
            model_name='availability',
            index=models.Index(fields=['practitioner', 'is_available'], name='NutriApp_av_practit_f721ed_idx'),
        ),
        migrations.AddIndex(
            model_name='availability',
            index=models.Index(fields=['specific_date', 'is_available'], name='NutriApp_av_specifi_5a8b66_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['date', 'status'], name='NutriApp_co_date_0e421a_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['client', 'date'], name='NutriApp_co_client__45e6a0_idx'),
        ),
        migrations.AddIndex(
            model_name='practitioner',
            index=models.Index(fields=['is_verified', 'city'], name='NutriApp_pr_is_veri_0695b7_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['consultation', 'rating'], name='NutriApp_re_consult_d50522_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['reviewer', 'created_at'], name='NutriApp_re_reviewe_14e3f2_idx'),
        ),
        migrations.AddConstraint(
            model_name='availability',
            constraint=models.CheckConstraint(condition=models.Q(('day_of_week__isnull', False), ('recurrence_type', 'weekly'), ('specific_date__isnull', True)), name='valid_weekly_availability'),
        ),
        migrations.AddConstraint(
            model_name='availability',
            constraint=models.CheckConstraint(condition=models.Q(('day_of_week__isnull', True), ('recurrence_type', 'one_time'), ('specific_date__isnull', False)), name='valid_one_time_availability'),
        ),
        migrations.AddConstraint(
            model_name='availability',
            constraint=models.CheckConstraint(condition=models.Q(('recurrence_type', 'unavailable'), ('specific_date__isnull', False)), name='valid_unavailable_block'),
        ),
        migrations.AddConstraint(
            model_name='availability',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='end_time_after_start_time'),
        ),
    ]
