# Generated by Django 5.2.11 on 2026-02-20 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("NutriApp", "0014_alter_availability_options_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="availability",
            name="valid_weekly_availability",
        ),
        migrations.RemoveConstraint(
            model_name="availability",
            name="valid_one_time_availability",
        ),
        migrations.RemoveConstraint(
            model_name="availability",
            name="valid_unavailable_block",
        ),
        migrations.RemoveConstraint(
            model_name="availability",
            name="end_time_after_start_time",
        ),
    ]
