# Generated by Django 6.0 on 2026-02-21 03:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NutriApp', '0015_remove_availability_valid_weekly_availability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practitioner',
            name='city',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='practitioner',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Hourly rate in selected currency', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='practitioner',
            name='user',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='practitioner', to=settings.AUTH_USER_MODEL),
        ),
    ]
